/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Swing;

import Application.Controller.Controller;
import Domain.SortStation;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Marcleking
 */
public class infoSortStationFrame extends javax.swing.JFrame { // Pourquoi c'est un Frame. Cette classe contient une méthode main()??

    private SortStation _sortStation;
    private ArrayList _sortStationList;
    private MainFrame _parent;
    
    /**
     * Creates new form infoSortStation
     */
    public infoSortStationFrame() {
        initComponents();
    }
    
    public infoSortStationFrame(SortStation sortStation, ArrayList sortStationList, MainFrame parent) {
        initComponents();
        
        this._sortStation = sortStation;
        this.setStationName(sortStation.getName());
        this.setStationDescription(sortStation.getDescription());
        this.setStationKgHMax(sortStation.getKgHMax());
        this.setStationNbExit(sortStation.getExit().size());
        
        this._parent = parent;
        this._sortStationList = sortStationList;
    }

    public void setStationDescription(String txtStationDescription) {
        this.txtStationDescription.setText(txtStationDescription);
    }

    public void setStationKgHMax(Float txtStationKgHMax) {
        this.txtStationKgHMax.setText(txtStationKgHMax.toString());
    }

    public void setStationName(String txtStationName) {
        this.txtStationName.setText(txtStationName);
    }

    public void setStationNbExit(Integer txtStationNbExit) {
        this.txtStationNbExit.setText(txtStationNbExit.toString());
    }
    
    public JPanel getPanel() {
        return this.panelInformation2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformation2 = new javax.swing.JPanel();
        btnDeleteStation = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStationDescription = new javax.swing.JTextArea();
        txtStationName = new javax.swing.JTextField();
        txtStationKgHMax = new javax.swing.JTextField();
        btnColorPciker = new javax.swing.JButton();
        txtStationNbExit = new javax.swing.JTextField();
        btnImgStation = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInformation2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInformation2.setPreferredSize(new java.awt.Dimension(216, 2));

        btnDeleteStation.setText("Supprimer");
        btnDeleteStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteStationMouseClicked(evt);
            }
        });
        btnDeleteStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStationActionPerformed(evt);
            }
        });

        txtStationDescription.setColumns(20);
        txtStationDescription.setRows(5);
        txtStationDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStationDescriptionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtStationDescription);

        txtStationName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStationNameKeyPressed(evt);
            }
        });

        txtStationKgHMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStationKgHMaxKeyPressed(evt);
            }
        });

        btnColorPciker.setText("Couleur");
        btnColorPciker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorPcikerMouseClicked(evt);
            }
        });
        btnColorPciker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorPcikerActionPerformed(evt);
            }
        });

        txtStationNbExit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStationNbExitKeyPressed(evt);
            }
        });

        btnImgStation.setText("Image");
        btnImgStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImgStationMouseClicked(evt);
            }
        });

        jButton4.setText("Matrice de tri");

        jLabel1.setText("Nom:");

        jLabel2.setText("Description:");

        jLabel3.setText("Nombre de sortie:");

        jLabel4.setText("Kg/h max:");

        javax.swing.GroupLayout panelInformation2Layout = new javax.swing.GroupLayout(panelInformation2);
        panelInformation2.setLayout(panelInformation2Layout);
        panelInformation2Layout.setHorizontalGroup(
            panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformation2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStationName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(txtStationKgHMax)
                    .addComponent(btnColorPciker, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStationNbExit, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImgStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInformation2Layout.createSequentialGroup()
                        .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInformation2Layout.setVerticalGroup(
            panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformation2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDeleteStation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStationKgHMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnColorPciker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStationNbExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImgStation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformation2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStationActionPerformed

    private void btnDeleteStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteStationMouseClicked
        this._sortStationList.remove(0);
        this._parent.cleanInformationPanel();
        this._parent.repaint();
    }//GEN-LAST:event_btnDeleteStationMouseClicked

    private void txtStationNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStationNameKeyPressed
        this._sortStation.setName(this.txtStationName.getText());
        this._parent.repaint();
    }//GEN-LAST:event_txtStationNameKeyPressed

    private void txtStationDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStationDescriptionKeyPressed
        this._sortStation.setDescription(this.txtStationDescription.getText());
    }//GEN-LAST:event_txtStationDescriptionKeyPressed

    private void txtStationKgHMaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStationKgHMaxKeyPressed
        String strKgHMax = this.txtStationKgHMax.getText();
        
        float kgHMax;
        try {
            kgHMax = Float.parseFloat(strKgHMax);
        } catch (NumberFormatException e) {
            kgHMax = this._sortStation.getKgHMax();
        }
        
        this._sortStation.setKgHMax(kgHMax);
    }//GEN-LAST:event_txtStationKgHMaxKeyPressed

    private void txtStationNbExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStationNbExitKeyPressed
        String strNbExit = this.txtStationNbExit.getText();
        
        int nbExit;
        try {
            nbExit = Integer.parseInt(strNbExit);            
        } catch (NumberFormatException e) {
            nbExit = this._sortStation.getExit().size();
        }
        
        this._sortStation.setExit(nbExit);
    }//GEN-LAST:event_txtStationNbExitKeyPressed

    private void btnColorPcikerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorPcikerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColorPcikerMouseClicked

    private void btnColorPcikerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorPcikerActionPerformed
        Color colorStation = JColorChooser.showDialog(null, "sdfsdf", this._sortStation.getColor());
        this._sortStation.setColor(colorStation);
        this._parent.repaint();
    }//GEN-LAST:event_btnColorPcikerActionPerformed

    private void btnImgStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImgStationMouseClicked
        JFileChooser filePicker = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG, GIF & PNG Images", "jpg", "gif", "png");
        filePicker.setFileFilter(filter);
        int responce = filePicker.showOpenDialog(this._parent);
        if(responce == JFileChooser.APPROVE_OPTION) {
           this._sortStation.setImg(filePicker.getSelectedFile().getAbsolutePath());
        }
        this._parent.repaint();
    }//GEN-LAST:event_btnImgStationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(infoSortStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(infoSortStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(infoSortStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(infoSortStationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new infoSortStationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorPciker;
    private javax.swing.JButton btnDeleteStation;
    private javax.swing.JButton btnImgStation;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInformation2;
    private javax.swing.JTextArea txtStationDescription;
    private javax.swing.JTextField txtStationKgHMax;
    private javax.swing.JTextField txtStationName;
    private javax.swing.JTextField txtStationNbExit;
    // End of variables declaration//GEN-END:variables

    
}
