/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation.Swing;

import Application.Controller.Controller;
import java.awt.Color;
import java.awt.geom.Point2D;
import java.util.Map;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Marcleking
 */
public class SortCenterParamPanel extends javax.swing.JFrame { // Pourquoi c'est un Frame. Cette classe contient une méthode main()??

    private MainFrame _parent;
    private Controller _controller;
    private Color _elementColor;
    
    
    /**
     * Creates new form infoSortStation
     */
    public SortCenterParamPanel() {
        initComponents();
    }
    
    public SortCenterParamPanel(Controller controller, MainFrame parent) {
        initComponents();
        
        this._controller = controller;
        
        Map<String, Object> infoElement = this._controller.getSelectedElementAttributes();
        
//        this.setElementName((String) infoElement.get("name"));
        this.setStationDescription((String) _controller.getSelectedElementAttribute("description"));
        this._elementColor = (Color) _controller.getSelectedElementAttribute("color");
        Point2D.Float point = (Point2D.Float)_controller.getSelectedElementAttribute("dimensions");
        this.txtXDimension.setText(Float.toString(point.x));
        this.txtYDimension.setText(Float.toString(point.y));
        
        this._parent = parent;
    }

    public void setStationDescription(String txtStationDescription)
    {
        this.txtStationDescription.setText(txtStationDescription);
    }
    
    public JPanel getPanel() {
        return this.panelInformation2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformation2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtStationDescription = new javax.swing.JTextArea();
        btnColorPciker = new javax.swing.JButton();
        btnImgStation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtYDimension = new javax.swing.JTextField();
        txtXDimension = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInformation2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelInformation2.setPreferredSize(new java.awt.Dimension(216, 2));

        txtStationDescription.setColumns(20);
        txtStationDescription.setRows(5);
        txtStationDescription.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtStationDescriptionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtStationDescription);

        btnColorPciker.setText("Couleur");
        btnColorPciker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColorPcikerMouseClicked(evt);
            }
        });
        btnColorPciker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorPcikerActionPerformed(evt);
            }
        });

        btnImgStation.setText("Image");
        btnImgStation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImgStationMouseClicked(evt);
            }
        });
        btnImgStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgStationActionPerformed(evt);
            }
        });

        jLabel2.setText("Description:");

        txtYDimension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYDimensionKeyPressed(evt);
            }
        });

        txtXDimension.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtXDimensionKeyPressed(evt);
            }
        });

        jLabel3.setText("Dimension");

        jLabel5.setText("Largeur");

        jLabel6.setText("Hauteur");

        javax.swing.GroupLayout panelInformation2Layout = new javax.swing.GroupLayout(panelInformation2);
        panelInformation2.setLayout(panelInformation2Layout);
        panelInformation2Layout.setHorizontalGroup(
            panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformation2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(btnColorPciker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImgStation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelInformation2Layout.createSequentialGroup()
                        .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(panelInformation2Layout.createSequentialGroup()
                                .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtXDimension, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelInformation2Layout.setVerticalGroup(
            panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformation2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorPciker)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImgStation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtXDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformation2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInformation2, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStationDescriptionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStationDescriptionKeyPressed
        _controller.setSelectedElementAttribute("description", txtStationDescription.getText());
    }//GEN-LAST:event_txtStationDescriptionKeyPressed

    private void txtStationNbExitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStationNbExitKeyPressed

    }//GEN-LAST:event_txtStationNbExitKeyPressed

    private void btnColorPcikerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColorPcikerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColorPcikerMouseClicked

    private void btnColorPcikerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorPcikerActionPerformed
        Color elementColor = JColorChooser.showDialog(null, "Veuillez choisir la couleur de la station", this._elementColor);
        _controller.setSelectedElementAttribute("color", elementColor);
//        this._controller.EditStation(
//            this.txtStationName.getText(), 
//            this.txtStationDescription.getText(), 
//            elementColor, 
//            null,
//            Float.valueOf(this.txtStationKgHMax.getText()),
//            null, null, null
//        );
        
        this._parent.repaint();
    }//GEN-LAST:event_btnColorPcikerActionPerformed

    private void btnImgStationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImgStationMouseClicked
        
    }//GEN-LAST:event_btnImgStationMouseClicked

    private void txtYDimensionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYDimensionKeyPressed
        float dimensionY;
        try {
            dimensionY = Float.parseFloat(this.txtYDimension.getText());
        } catch (NumberFormatException e) {
            return;
        }

        this._controller.EditStation(null, null, null, null, null, null, Float.valueOf(this.txtXDimension.getText()), Float.valueOf(dimensionY));
        this._parent.repaint();
    }//GEN-LAST:event_txtYDimensionKeyPressed

    private void txtXDimensionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtXDimensionKeyPressed
        float dimensionX;
        try {
            dimensionX = Float.parseFloat(this.txtXDimension.getText());
        } catch (NumberFormatException e) {
            return;
        }

        this._controller.EditStation(null, null, null, null, null, null, Float.valueOf(dimensionX), Float.valueOf(this.txtYDimension.getText()));
        this._parent.repaint();
    }//GEN-LAST:event_txtXDimensionKeyPressed

    private void btnImgStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgStationActionPerformed
    JFileChooser filePicker = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG, GIF & PNG Images", "jpg", "gif", "png");
        filePicker.setFileFilter(filter);
        int responce = filePicker.showOpenDialog(this._parent);
        if(responce == JFileChooser.APPROVE_OPTION) {
            _controller.setSelectedElementAttribute("image", filePicker.getSelectedFile().getAbsolutePath());
//            this._controller.EditStation(
//                this.txtStationName.getText(), 
//                this.txtStationDescription.getText(), 
//                null, 
//                filePicker.getSelectedFile().getAbsolutePath(),
//                Float.valueOf(this.txtStationKgHMax.getText()),
//                null, null, null
//            );
        }
        this._parent.repaint();
    }//GEN-LAST:event_btnImgStationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortCenterParamPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortCenterParamPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortCenterParamPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortCenterParamPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortCenterParamPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorPciker;
    private javax.swing.JButton btnImgStation;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelInformation2;
    private javax.swing.JTextArea txtStationDescription;
    private javax.swing.JTextField txtXDimension;
    private javax.swing.JTextField txtYDimension;
    // End of variables declaration//GEN-END:variables

    
}
